### ISSUE TITLE
How can I help...

### ISSUE THREAD

**Issue by tremenyi** [hypertidy/tidync#18]
Hi MIke, how can I help.  I'll need a bit of a lesson in exactly what is useful and what isnt...

**Comment by mdsumner** [comment]
At the moment, the best help is to do some checking against a lot of different files. 

To see the latest behaviour for first-access and activating a grid, we need this branch installed: 

```
devtools::install_github("hypertidy/tidync@tidyfile-delay")
library(tidync)
somefile <- "epic_grid_splat.nc"
```

Then, the two main things to see if they work are 

```R
tidync(some_file)

tidync(some_file) %>% activate("D1,D2")

```

In concrete terms, with an in-built example file (and hey, look this works!)

```R
ufile <- system.file("extdata", "unidata", "madis-hydro.nc", package = "tidync")
tidync(ufile)

## also make sure we can active a new grid, this is the dimension ref comma separated (no brackets)
tidync(ufile) %>% activate("D3,D12")

```

I'm hoping to soon make it possible to do 

```R
tidync(ufile) %>% activate(3)  ## where the 3rd grid is used

tidync(ufile) %>% activate(varname) ## where variable "varname" is used to find the grid to activate

```


None of the filter or polygon lookup or tibble stuff works in this branch, but it does work the "old way" in the master branch.

**Comment by mdsumner** [comment]
master branch now has the new scheme, give it a go!

**Comment by mdsumner** [comment]
Ok, now for real it's functional again!  @tremenyi 

Any feedback is helpful, even if you get nowhere. I'll be polishing
