### ISSUE TITLE
Data source volume

### ISSUE THREAD

**Issue by tremenyi** [hypertidy/tidync#20]
Return estimated total data volume of "Data Source Name" (single file? many files? database? <- would it work for a database?)

**Comment by tremenyi** [comment]
So far the solution is to return the total number of data points ( prod(dims) ).  
This is because it matter if each data point is represented as a logical, integer or double, and this cannot be easily determined without loading in some data...

**Comment by mdsumner** [comment]
This definitely would benefit from a multi-file capability as well. There might be other general capability, since it is a very data-base-y thing to collect() - maybe some of the dplyr::explain idioms have similar?

**Comment by mdsumner** [comment]
I have seen string variables here and in non-contrived examples: 

https://stat.ethz.ch/pipermail/r-sig-geo/2014-August/021521.html

**Comment by mdsumner** [comment]
We can actually exactly determine the type and resulting size, but it's complicated by whether or the data get scaled on import, and what the translation from the types NetCDF (and C) has to the smaller set R has.

**Comment by mdsumner** [comment]
The upfront output summary gives an indication of what's coming
