### ISSUE TITLE
Size limit

### ISSUE THREAD

**Issue by tremenyi** [hypertidy/tidync#22]
There needs to be a limit to the amount of data read into memory by default, and a 'relatively' easy way to manipulate this.  Focus on 'small' files (<1e9 bytes) might be a good working solution.  Assumes >1e9 bytes avaialble at user end... This ok?

**Comment by mdsumner** [comment]
I put one in, it's just hardcoded and only asks if the session is interactive. We can copy what raster does, but at some level you don't want to stop, ever
