### ISSUE TITLE
Thredds

### ISSUE THREAD

**Issue by tremenyi** [hypertidy/tidync#24]
Can this approach handle being pointed at a thredds server

**Comment by mdsumner** [comment]
Minute example

```R
library(tidync)
u <- "http://coastwatch.pfeg.noaa.gov/erddap/griddap/erdQSwind3day"
(unc <- tidync(u))

unc %>% activate("D2")

```

filter doesn't work, "Write to read only". 

This older example had more: 

https://gist.github.com/mdsumner/edec338374ac1b4ee7c9c2b42be6030e

There's something I've forgotten about why this worked before with ncdump, but it might be with ncdf4 ...

**Comment by mdsumner** [comment]
Should work ok now!
