### ISSUE TITLE
ncdump dependency not installing correctly

### ISSUE THREAD

**Issue by JustBerkhout** [hypertidy/tidync#48]
is the remotes mechanism set properly?

**Comment by mdsumner** [comment]
I can't see why this isn't working, @JustBerkhout can you list your session info?

Run this in a fresh instance of R and post the output here please, when you have a chance: 

```R
devtools::session_info()
```

This will give me some clues about how I should test a fresh install.

**Comment by mdsumner** [comment]
I think I have it, my instructions should have

```R
devtools::install_github("hypertidy/tidync", dependencies = TRUE)
```

(It's hard to unpick an existing installation to test this, so don't bother if it's already working for you). 

I'll update the readme. 

Thanks!
