### ISSUE TITLE
In hyper_slice() give option not to collapse a dimension of size 1

### ISSUE THREAD

**Issue by rmendels** [hypertidy/tidync#65]
Here is an example showing the dimension collapse:

```{r}
myURL <- 'https://coastwatch.pfeg.noaa.gov/erddap/griddap/erdMBsstd1day.nc?sst[(2018-02-25T12:00:00Z):1:(2018-02-25T12:00:00Z)][(0.0):1:(0.0)][(30):1:(45)][(230):1:(245)]'
download.file(myURL, destfile = 'sst.nc', mode = 'wb')
sstFile <- tidync('sst.nc')
junk <- hyper_slice(sstFile)
str(junk)
```

It comes back with:

List of 1
 $ sst: num [1:601, 1:601, 1:4] 14.8 NA NA NA NA ...

In some settings,  such as wind,  though the altitude variable is only size 1 its value is important as it has the altitude where the wind measure is taken,  and could be getting combined with other data, there should be an option not to collapse the array.  In ncdf4 for example, in the function ncar_get()  there is the option "collapse_degen=TRUE"

**Comment by mdsumner** [comment]
Indeed, that's definitely supposed to be available!  Will fix, thanks

**Comment by mdsumner** [comment]
Thanks again, hyper_slice gains the argument `drop`, TRUE by default. I've used it enough now to be happy, but it's only in branch ropensci-review, for now.

**Comment by mdsumner** [comment]
Use `drop = FALSE` in `hyper_array` (replaces `hyper_slice`). Thanks!
