### ISSUE TITLE
awesome example file - easyncdf

### ISSUE THREAD

**Issue by mdsumner** [hypertidy/tidync#67]
```R

x <- tidync(filename) %>% 
  activate("v-component_of_wind_isobaric_ens") %>% 
  hyper_filter(time = between(time, 0, 12), 
               ens = between(ens, 1, 3), 
              # lat = between(lat, 42, 45), 
              # lon = between(lon, 233, 235), 
               isobaric1 = between(isobaric1, 10000, 30000), 
               time2 = between(time2, 18, 24), 
               height_above_ground = height_above_ground == 2) %>% 
  
  hyper_tbl_cube()
library(ggplot2)
ggplot(as_tibble(x), aes(lon, lat, fill = `v-component_of_wind_isobaric_ens`)) + geom_raster() + facet_wrap(isobaric1 ~ time)

```

@potterzot you might be interested, lots to discuss!

**Comment by potterzot** [comment]
@mdsumner ah, thanks! Looks exciting. Some end to the laborious direct interfacing with ncdf4 would be really nice. I'll try `tidync` out on my data tomorrow. Happy to discuss and/or contribute effort if needed.

**Comment by potterzot** [comment]
This looks great and works super well for the project I'm working on right now!

It looks like you're in the process of adding this to rOpenSci? I'd be interested in helping make that happen if it hasn't already. I contributed some code to them for accessing [GEFS data](https://github.com/ropensci/rnoaa/blob/master/R/gefs.R) in ncdf4 format.

One thing that might be nice would be an estimated size of the returned object, either in terms of rows or disk space (that'd be harder I imagine). For example, it could look like:
```
library(tidync)
library(dplyr)

filename <- "tests/data/test.nc4"
x <- tidync(filename) %>% 
  activate("v-component_of_wind_isobaric_ens") %>% 
  hyper_filter(time = between(time, 0, 12), 
               lat = between(lat, 42, 45), 
               lon = between(lon, 233, 235), 
               isobaric1 = between(isobaric1, 10000, 30000), 
               #time2 = between(time2, 18, 24), 
               #height_above_ground = height_above_ground == 2),
               ens = between(ens, 1, 3)) %>%
  expected_size()
  #hyper_tibble()

# Returns something like:
# >                  rows    columns
# > expected size    432       6
```

In the README you caution against pulling data without checking size but don't mention an easy way to check size.

**Comment by mdsumner** [comment]
Thanks, really appreciate that! There is a count of the pixel.next to the summary, but that that didn't get enough attention - I wrote it very early on and it wasn't well done. A big read will stop and see if you really want to proceed, but it's not smart about the test.

**Comment by mdsumner** [comment]
I'm now using this file as a standard test, along with stars: https://github.com/hypertidy/tidync/issues/68#issuecomment-381399429
